[package]
name = "kv_store"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
axum = "0.8.4"
openraft = { version = "0.9", features = ["serde", "storage-v2"]  }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
